# Generated by Django 5.0.6 on 2024-08-04 07:09

import ravi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0005_remove_customerprofile_random_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='ref1_mobile_number',
            new_name='ref1_mobilenumber',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='ref1_person_name',
            new_name='ref1_personname',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='ref2_mobile_number',
            new_name='ref2_mobilenumber',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='ref2_person_name',
            new_name='ref2_personname',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='random_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hlbasicdetailform',
            name='full_name',
            field=models.CharField(max_length=25, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='hlbasicdetailform',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_pan]),
        ),
        migrations.AlterField(
            model_name='hlbasicdetailform',
            name='required_loan_amount',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='aadhar_card_number',
            field=models.CharField(max_length=12, validators=[ravi.models.validate_aadhar_number]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='aadhar_pincode',
            field=models.CharField(max_length=6, validators=[ravi.models.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='company_name',
            field=models.CharField(max_length=100, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='current_address_pincode',
            field=models.CharField(max_length=6, validators=[ravi.models.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='date_of_birth',
            field=models.DateField(validators=[ravi.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='father_name',
            field=models.CharField(max_length=100, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='first_name',
            field=models.CharField(max_length=100, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='last_name',
            field=models.CharField(max_length=100, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='net_salary',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='office_address_pincode',
            field=models.CharField(max_length=6, validators=[ravi.models.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='pan_card_number',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_pan]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='ref1_mobile',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='ref1_name',
            field=models.CharField(max_length=100, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='ref2_mobile',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='ref2_name',
            field=models.CharField(max_length=100, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='required_loan_amount',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='running_emis',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='plbasicdetailform',
            name='full_name',
            field=models.CharField(max_length=25, validators=[ravi.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='plbasicdetailform',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_pan]),
        ),
        migrations.AlterField(
            model_name='plbasicdetailform',
            name='required_loan_amount',
            field=models.CharField(max_length=10, validators=[ravi.models.validate_amount]),
        ),
    ]
