# Generated by Django 5.0.6 on 2024-08-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0006_rename_ref1_mobile_number_customerprofile_ref1_mobilenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='ref1_mobilenumber',
            new_name='ref1_mobile_number',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='ref1_personname',
            new_name='ref1_person_name',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='ref2_mobilenumber',
            new_name='ref2_mobile_number',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='ref2_personname',
            new_name='ref2_person_name',
        ),
    ]
